services:
  mysql:
    image: "mysql:latest"
    container_name: sabichao_db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
  app:
    container_name: sabichao_backend
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '33109:3000'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mysql
