services:
  mysql:
    image: "mysql:8.0"
    container_name: sabichao_db
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  app:
    container_name: sabichao_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_DOCKER_PORT}:3000'
    environment:
      - SECRET=${SECRET}
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
    command: npm run start:dev
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network   

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
